spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password: 
      driver-class-name: org.h2.Driver
       
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.show_sql]': true    
      '[hibernate.format_sql]': true    
      #'[hibernate.highlight_sql]': true
   
# data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 50 
logging:
  level:
    root: info
    '[org.hibernate.SQL]': info
    '[org.hibernate.orm.jdbc.bind]': trace
